[workspace]
resolver = "2"
members = [
    "basic-projects",
    "ownership-projects",
    "web-projects",
    "game-projects",
    "desktop-projects",
    "wasm-projects",
    "advanced-projects",
    "tools",
    "experiments"
]

[workspace.package]
version = "0.1.0"
edition = "2024"